### ISSUE TITLE
服务会断掉

### ISSUE THREAD

**Issue by CAH-FlyChen** [Aimeast/GitCandy#18]
我做了jenkins和gitcandy的整合，定期从gitcandy上获取代码。但发现每过一定的时间后，jenkins就无法连上git服务器。此时，手动访问gitcandy网站，然后jenkins就又可以连接上服务器了。使用的是SSh

**Comment by Aimeast** [comment]
是否使用了ssh链接？具体情况是什么样的？

**Comment by CAH-FlyChen** [comment]
解决方法：写一个gitcandy的任务（实现IJob），定期访问网站。代码参考：https://gitcandy.com/Repository/Blob/GitCandy.Jobs/master/GitCandy.Jobs/KeepAliveJob.cs
https://gitcandy.com/Repository/Blob/GitCandy/dev/GitCandy/Base/MefDependencyResolver.cs
